# Generated by Django 5.1.1 on 2024-12-20 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.DurationField(help_text='Duration in minutes')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='service_photos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bio',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='working_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='working_start_time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(related_name='appointments', to='appointments.service'),
        ),
    ]
