# Generated by Django 5.1.1 on 2025-01-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NailDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, default='path/to/default/photo.jpg', null=True, upload_to='nail_designs/')),
            ],
        ),
    ]
