# Generated by Django 5.1.1 on 2025-01-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_nail_design_alter_service_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='services',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
